title: Server config options
blocks:
  - _type: text
    alt: Server config options
    value: "**Server config options**"
  - _type: text
    alt: Minify json
    value: |-
      **Minify json**

      Allows you to minify the json?
  - _type: text
    alt: Ghost monument
    value: >-
      **Ghost monument**


      **Toggles the random teleporting of the tardis exterior when the engine is
      phasing**
  - _type: text
    alt: Lock dimensions
    value: |-
      **Lock dimensions**

      Enables the locking of dimensions for the tardis
  - _type: text
    alt: Enable Rwf
    value: |-
      **Enable rwf**

      (Broken Do NOT USE)

      allows you enable the real world flight of the tardis
  - _type: text
    alt: can tnt teleport into through doors
    value: |-
      **can tnt teleport into through doors**

      Enables whether lit tnt can enter the tardis doors
  - _type: text
    alt: Enable hypercubes
    value: |-
      **Enable hypercubes**

      Enables whether or not hypercubes are obtainable
  - _type: text
    alt: Travel per tick
    value: |-
      **Travel per tick**

      Default Value: 2

      Changes the rate of Travel per tick
  - _type: text
    alt: Send Bulk
  - _type: text
    alt: Max amount of tardises
    value: |-
      **Max amount of tardises**

      \-1 Defaults to no limit and is the default option

      Changes how many tardises worlds can have
  - _type: text
    alt: Disable safegards
    value: |-
      **Disable safegards**

      Disables safegards (Pretty self explanatory)
  - _type: text
    alt: Enviroment projector black list
    value: "**Enviroment projector black list**"
sidebar:
  open: false
  exclude: false
